spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/jwtdemo
    username: root
    password: MyNewPass
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update


jwt:
  secret: pleasebro
